export let columns = [
  {
    dataField: 'id',
    text: '#',
    classes: "",
    sort: true,
    align: "center",
    headerAlign: "center",
    formatter: null,
  },
  {
    dataField: 'firstName',
    text: 'First Name',
    classes: "",
    sort: true,
    align: "center",
    headerAlign: "center",
    formatter: null,
  },
  {
    dataField: 'lastName',
    text: 'Last Name',
    classes: "",
    sort: true,
    align: "center",
    headerAlign: "center",
    formatter: null,
  },
  {
    dataField: 'description',
    text: 'Description',
    classes: "",
    sort: true,
    align: "center",
    headerAlign: "center",
    formatter: null,
  },
  {
    dataField: 'fileName',
    text: 'File Name',
    classes: "",
    sort: true,
    align: "center",
    headerAlign: "center",
    formatter: null,
  },
  {
    dataField: 'action',
    text: 'Action',
    classes: "",
    sort: true,
    align: "center",
    headerAlign: "center",
    formatter: ()=>{},
  }
]